sudo: required
services:
  - docker
language: python
python:
  - "3.5"
env:
  COMPOSE_VERSION: 1.4.1
before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - cd tests/ && docker-compose up -d
install:
  - pip install coveralls pep8
script:
  - while ! nc -z 127.0.0.1 10051; do sleep 1; done
  - pwd
  - coverage run tests/runtests.py
  - pep8 ZabbixSender/ZabbixSender.py
  - pep8 ZabbixSender/ZabbixPacket.py
after_success:
  coveralls
notifications:
  email:
    - maksim77ster@gmail.com
