sudo: required
services:
  - docker
language: python
python:
  - "3.5"
env:
  COMPOSE_VERSION: 1.4.1
before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
install:
  - pip install ZabbixSender
script:
  - docker-compose up -d
  - sleep 10
  - python3 git_tests.py
notifications:
  email:
    - maksim77ster@gmail.com
